-- =======================================================
-- CitizenDoc - MySQL Database Seed Data
-- =======================================================

USE citizendoc_db;

-- 1. Demo User (Password: password123 with bcrypt hash)
INSERT INTO users (id, name, email, password, state, avatar) VALUES
(1, 'Aarav Sharma', 'aarav.sharma@example.com', '$2a$10$7Z8l1Uq5aE78Z4VvO6ZquOSQnK2f2P8vE8Fh3zQWd8VlY/y7kK5C.', 'Maharashtra', 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=150&auto=format&fit=crop&q=80')
ON DUPLICATE KEY UPDATE name=VALUES(name);

-- 2. 12 Documents
INSERT INTO documents (id, name, slug, category, description, processing_time, fee, official_link, issuing_authority, icon, eligibility_overview) VALUES
(1, 'Aadhaar Card', 'aadhaar-card', 'Identity & Proof', '12-digit unique identity number issued by UIDAI to all Indian residents, serving as proof of identity and address across India.', '15 to 30 Days', 'Free (New) / ₹50 (Update)', 'https://myaadhaar.uidai.gov.in/', 'Unique Identification Authority of India (UIDAI)', 'Fingerprint', 'All resident individuals living in India for at least 182 days in the preceding 12 months, including newborns and minors.'),
(2, 'PAN Card', 'pan-card', 'Financial & Tax', 'Permanent Account Number issued by Income Tax Department, mandatory for tax filing, opening bank accounts, and high-value financial transactions.', '7 to 15 Days (Instant e-PAN in 10 mins)', '₹107 (Physical) / Free (Instant e-PAN)', 'https://www.onlineservices.nsdl.com/paam/endUserRegisterContact.html', 'Income Tax Department (NSDL / UTIITSL)', 'CreditCard', 'Any Indian citizen, NRI, minor, or legal entity earning taxable income in India.'),
(3, 'Voter ID', 'voter-id', 'Civic & Electoral', 'Electors Photo Identity Card (EPIC) issued by the Election Commission of India, enabling voting rights in national, state, and local elections.', '15 to 30 Days', 'Free of cost', 'https://voters.eci.gov.in/', 'Election Commission of India (ECI)', 'Vote', 'Indian citizens aged 18 years or older on qualifying date, ordinarily resident in the constituency.'),
(4, 'Passport', 'passport', 'Travel & Identity', 'Official travel document issued by the Ministry of External Affairs for international travel and authoritative proof of Indian citizenship.', '10 to 30 Days (Normal) / 3 to 7 Days (Tatkaal)', '₹1,500 (Normal) / ₹3,500 (Tatkaal)', 'https://www.passportindia.gov.in/', 'Ministry of External Affairs (MEA)', 'Plane', 'Indian citizens by birth, descent, or naturalization with no disqualifying criminal record.'),
(5, 'Driving Licence', 'driving-licence', 'Transport & Mobility', 'Official authorization issued by Regional Transport Offices (RTO) permitting individuals to drive motor vehicles on public roads.', '15 to 30 Days (After driving test)', '₹200 (LL) + ₹300 (DL) + ₹200 (Test)', 'https://parivahan.gov.in/parivahan/', 'Ministry of Road Transport & Highways (MoRTH)', 'Car', 'Age 16+ for Gearless 50cc; Age 18+ for LMV; Age 20+ for Commercial with valid Learner Licence.'),
(6, 'Birth Certificate', 'birth-certificate', 'Vital Records', 'Official legal record verifying the birth date, location, parentage, and gender of a child, fundamental for all future identity registrations.', '7 to 21 Days', 'Free (within 21 days) / ₹5 to ₹50 (delayed)', 'https://crsorgi.gov.in/web/index.php/auth/login', 'Civil Registration System (CRS)', 'Baby', 'Any child born within the municipal jurisdiction or state boundary, reported by parents or hospitals.'),
(7, 'Income Certificate', 'income-certificate', 'Welfare & Subsidies', 'Government-certified proof of total annual family earnings, required for scholarship applications, fee waivers, and welfare welfare schemes.', '10 to 15 Days', '₹20 to ₹60 (Varies by State)', 'https://edistrict.gov.in/', 'Revenue Department / Tahsildar / SDM', 'TrendingUp', 'Residents of the respective state with documented or self-declared annual household income sources.'),
(8, 'Community Certificate', 'community-certificate', 'Welfare & Subsidies', 'Legal certificate validating caste status (SC/ST/OBC/EWS) to claim affirmative action reservations in education and government jobs.', '15 to 30 Days', '₹30 to ₹75', 'https://services.india.gov.in/', 'Revenue Department / District Magistrate', 'Shield', 'Indian citizens belonging to recognized Scheduled Castes, Scheduled Tribes, OBC, or EWS.'),
(9, 'Domicile Certificate', 'domicile-certificate', 'Certificates & Rights', 'Official verification that a person has permanent residence or has resided in a specific state/UT for a continuous specified statutory period.', '15 to 25 Days', '₹30 to ₹50', 'https://edistrict.gov.in/', 'District Magistrate / Sub-Divisional Officer', 'Home', 'Continuous residency in the state for 5 to 15 years or ownership of immovable property.'),
(10, 'Ration Card', 'ration-card', 'Welfare & Food Security', 'Document issued to eligible households under the National Food Security Act (NFSA) for subsidized food grains and targeted welfare entitlements.', '20 to 30 Days', '₹15 to ₹45', 'https://nfsa.gov.in/', 'Department of Food, Civil Supplies & Consumer Affairs', 'ShoppingBag', 'Families residing within state jurisdiction who do not possess any other active ration card.'),
(11, 'Marriage Certificate', 'marriage-certificate', 'Vital Records', 'Official legal declaration establishing the solemnization and valid union of two individuals under Hindu Marriage Act or Special Marriage Act.', '7 to 30 Days', '₹100 to ₹250', 'https://services.india.gov.in/', 'Registrar of Marriages / Revenue Department', 'HeartHandshake', 'Groom age 21+, Bride age 18+, mutual consent, not within prohibited degrees of relationship.'),
(12, 'Death Certificate', 'death-certificate', 'Vital Records', 'Official document stating the date, location, and certified cause of an individual demise, critical for inheritance, insurance, and legal closures.', '7 to 15 Days', 'Free (within 21 days) / ₹10 to ₹50 (delayed)', 'https://crsorgi.gov.in/', 'Civil Registration System / Municipal Health Dept', 'FileText', 'Next of kin, family member, doctor, or authorized hospital representative.')
ON DUPLICATE KEY UPDATE name=VALUES(name);

-- 3. Demo Saved Applications
INSERT INTO saved_applications (id, user_id, document_id, application_id, applied_date, state, status, notes, tracking_number) VALUES
(1, 1, 2, 'APP-PAN-2026-89412', '2026-08-15', 'Maharashtra', 'Approved', 'Applied via Protean NSDL Instant e-PAN with Aadhaar e-KYC. Digital e-PAN received via email.', 'NSDL88941249A'),
(2, 1, 4, 'APP-PAS-2026-44109', '2026-08-18', 'Maharashtra', 'In Review', 'PSK Pune visit completed successfully at Counter A, B & C. Police verification scheduled for next Monday.', 'PN2078491275926'),
(3, 1, 5, 'APP-DL-2026-11823', '2026-08-01', 'Maharashtra', 'Completed', 'Smart card DL delivered via Speed Post. Digital copy verified on DigiLocker.', 'MH12-20260011823'),
(4, 1, 3, 'APP-VOT-2026-67319', '2026-08-24', 'Maharashtra', 'Submitted', 'Form 6 submitted online on ECI Voters Portal. Waiting for BLO field verification.', 'ECI-F6-2026-67319'),
(5, 1, 7, 'APP-INC-2026-30214', '2026-08-25', 'Maharashtra', 'Draft', 'Draft application saved with salary slips. Need to attach latest Form 16 before final submission.', 'EDIST-MH-30214')
ON DUPLICATE KEY UPDATE status=VALUES(status);
